### ISSUE TITLE
Unintuitive default timeout warning threshold

### ISSUE THREAD

**Issue by WhiffleFish** [LAMDA-POMDP/AdaOPS.jl#5]
https://github.com/LAMDA-POMDP/AdaOPS.jl/blob/e8593ebec82f064efd08b2b34301dbb1011281aa/src/AdaOPS.jl#L143

https://github.com/LAMDA-POMDP/AdaOPS.jl/blob/e8593ebec82f064efd08b2b34301dbb1011281aa/src/planner.jl#L15

Default results in timeout warnings whenever planning time exceeds `2*T_max^2` . For planning times less than 1 second this results in far too many warnings printed to screen.

For example, if we have `T_max = 0.01`, then the warning is triggered whenever planning time exceeds 0.0002s, which would be at every action call, provided that the `max_trials` option is set to be sufficiently high.

Also, it may be worth looking at [this issue](https://github.com/JuliaPOMDP/POMCPOW.jl/issues/29)  seeing as CPUTime seems to have a lot of overhead, especially for problems with quick gen functions

**Comment by Wu-Chenyang** [comment]
Thank you for pointing it out! It is a bug, and I will fix it soon.
Concerning the CPUTime package, I think it is necessary when multiple tasks compete for resources. But anyway, a `timer` option could be helpful.
