### ISSUE TITLE
Running LaserTag benchmark with KLD

### ISSUE THREAD

**Issue by marisgg** [LAMDA-POMDP/AdaOPS.jl#7]
Hi!

Thanks for publishing the code with nice instructions. I have a question about running LaserTag, which is one of the benchmarks in the paper which by its results seems to benefit from all extensions; KLD, AR, and BP.

Please excuse me if I'm misunderstanding. If I run the planner on LaserTag, it never seem to actually use the KLD code as `N==0` is always true in this snippet:

```
function resample!(b::B, p::AdaOPSPlanner{S,A,O,M,N}) where {B,S,A,O,M<:POMDP{S,A,O},N}
    if N == 0
        # the number of resampled particles is default to p.sol.m_max
        return resample!(p.resampled, b, p.pomdp, p.rng)
    else
        fill!(p.access_cnt, 0)
        return kld_resample!(b, p)
    end
end
```

What could be the cause of this; my instantiation of LaserTag or the AdaOPS planner, e.g. the `m_max` hyperparameter or something else?

I've looked into the supplementary material, but only `m_min` and `delta` are specified. Large values of `m_max` also don't seem to affect this. I'm very curious about how your instantiation of AdaOPS used for the LaserTag benchmark was specifically.

Thanks in advance.

**Comment by Wu-Chenyang** [comment]
To use KLD resampling, you should first define a grid and pass it to AdaOPSSolver. The following grid is what we used in LaserTag,
```julia
Base.convert(::Type{SVector{2, Float64}}, s::LTState) = SVector{2,Float64}(s.opponent)
grid = StateGrid([2:7;], [2:11;])
```

**Comment by marisgg** [comment]
Thanks!
